In [1]:
import pandas as pd
import geopandas as gpd
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
hibiya = pd.read_csv('data/gmonpro_20221207_085354_Sim1_44011.csv', header=None)

In [4]:
hibiya = hibiya[0].str.split(';', expand=True)
hibiya.columns = hibiya.iloc[0]
hibiya.drop(0, inplace=True)
hibiya.reset_index(drop=True, inplace=True)
hibiya.rename(columns={'PCI/PSC/BSIC':'PCI', 'RSRP/RSCP':'RSRP', 'RSRQ/ECIO':'RSRQ', 'SNR':'SINR', 'LAT':'LAT_org', 'LON':'LON_org', 'TIME':'TIME_org'}, inplace=True)
hibiya.insert(0, 'LON', hibiya['LON_org'])
hibiya.insert(0, 'LAT', hibiya['LAT_org'])
hibiya.insert(0, 'TIME', hibiya['TIME_org'])
hibiya.drop(['LON_org', 'LAT_org', 'TIME_org'], axis=1, inplace=True)

In [5]:
hibiya.head(3)

,TIME,LAT,LON,PLMN,SYSTEM,XCI,xNBID,LOCAL_CID,LAC/TAC,PCI,ARFCN,BAND,RSSI,RSRP,RSRQ,SINR,CQI,TA,DISTANCE,DELTA_AZI,SPEED,GPS_ACCURACY,UL,DL,BANDWIDTH,BANDWIDTHS,CA,NR_STATE,NARFCN,NR_BAND,NR_PCI,NR_SS_RSRP,NR_SS_RSRQ,NR_SS_SINR,NR_CSI_RSRP,NR_CSI_RSRQ,NR_CSI_SINR,CLF_LABEL,CLF_LOC,CLF_DESC,DATE,ROAMING
0,08:53:54,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,61,1227,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME
1,08:53:55,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,46,953,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME
2,08:53:56,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-84,-6,1.6,,180,,,0,1200,56,1084,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME

In [6]:
hibiya = gpd.GeoDataFrame(hibiya, geometry= gpd.points_from_xy(hibiya['LON'], hibiya['LAT']))

In [7]:
hibiya.head(3)

,TIME,LAT,LON,PLMN,SYSTEM,XCI,xNBID,LOCAL_CID,LAC/TAC,PCI,ARFCN,BAND,RSSI,RSRP,RSRQ,SINR,CQI,TA,DISTANCE,DELTA_AZI,SPEED,GPS_ACCURACY,UL,DL,BANDWIDTH,BANDWIDTHS,CA,NR_STATE,NARFCN,NR_BAND,NR_PCI,NR_SS_RSRP,NR_SS_RSRQ,NR_SS_SINR,NR_CSI_RSRP,NR_CSI_RSRQ,NR_CSI_SINR,CLF_LABEL,CLF_LOC,CLF_DESC,DATE,ROAMING,geometry
0,08:53:54,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,61,1227,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288)
1,08:53:55,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,46,953,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288)
2,08:53:56,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-84,-6,1.6,,180,,,0,1200,56,1084,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288)

In [8]:
tokyo = gpd.read_file('data/tokyo_220101.geojson')

In [9]:
tokyo.shape

(6177, 6)

In [10]:
tokyo.columns

Index(['N03_001', 'N03_002', 'N03_003', 'N03_004', 'N03_007', 'geometry'], dtype='object')

In [11]:
tokyo[['N03_001', 'N03_002', 'N03_003', 'N03_004', 'N03_007']].head()

  N03_001  N03_002 N03_003 N03_004 N03_007
0     東京都      NaN     NaN     NaN     NaN
1     東京都      NaN     NaN    千代田区   13101
2     東京都      NaN     NaN     中央区   13102
3     東京都      NaN     NaN      港区   13103
4     東京都      NaN     NaN      港区   13103

In [12]:
tokyo['geometry'].head(10)

0    MULTIPOLYGON (((136.07396 20.42276, 136.07388 ...
1    POLYGON ((139.77287 35.70370, 139.77279 35.703...
2    POLYGON ((139.78341 35.69645, 139.78459 35.696...
3    POLYGON ((139.77129 35.62841, 139.77128 35.628...
4    POLYGON ((139.76689 35.62774, 139.76718 35.627...
5    POLYGON ((139.77022 35.63199, 139.77046 35.631...
6    POLYGON ((139.75801 35.63380, 139.75801 35.633...
7    POLYGON ((139.75852 35.63380, 139.75852 35.633...
8    POLYGON ((139.76667 35.63298, 139.76654 35.632...
9    POLYGON ((139.77659 35.63611, 139.77661 35.636...
Name: geometry, dtype: geometry

In [13]:
tokyo['geometry'].tail(10)

6167    POLYGON ((140.05250 31.43806, 140.05246 31.438...
6168    POLYGON ((140.05377 31.43815, 140.05371 31.438...
6169    POLYGON ((140.05201 31.43835, 140.05196 31.438...
6170    POLYGON ((140.05076 31.44022, 140.05077 31.440...
6171    POLYGON ((140.05065 31.44218, 140.05060 31.442...
6172    POLYGON ((140.34167 29.79385, 140.34161 29.793...
6173    POLYGON ((139.85036 35.65624, 139.85034 35.655...
6174    POLYGON ((139.81367 35.57886, 139.81343 35.578...
6175    POLYGON ((139.82664 35.59760, 139.82700 35.597...
6176    POLYGON ((139.81286 35.59047, 139.81355 35.589...
Name: geometry, dtype: geometry

In [14]:
final = gpd.sjoin(hibiya, tokyo[['N03_001', 'N03_004', 'geometry']], how='left', op='within')

In [15]:
print(hibiya.shape)
print(final.shape)

(520, 43)
(1040, 46)

In [16]:
final.head()

,TIME,LAT,LON,PLMN,SYSTEM,XCI,xNBID,LOCAL_CID,LAC/TAC,PCI,ARFCN,BAND,RSSI,RSRP,RSRQ,SINR,CQI,TA,DISTANCE,DELTA_AZI,SPEED,GPS_ACCURACY,UL,DL,BANDWIDTH,BANDWIDTHS,CA,NR_STATE,NARFCN,NR_BAND,NR_PCI,NR_SS_RSRP,NR_SS_RSRQ,NR_SS_SINR,NR_CSI_RSRP,NR_CSI_RSRQ,NR_CSI_SINR,CLF_LABEL,CLF_LOC,CLF_DESC,DATE,ROAMING,geometry,index_right,N03_001,N03_004
0,08:53:54,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,61,1227,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),0,東京都,NaN
0,08:53:54,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,61,1227,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
1,08:53:55,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,46,953,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),0,東京都,NaN
1,08:53:55,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,46,953,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
2,08:53:56,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-84,-6,1.6,,180,,,0,1200,56,1084,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),0,東京都,NaN

In [17]:
final = final.loc[final.index.duplicated()]

In [18]:
final.head()

,TIME,LAT,LON,PLMN,SYSTEM,XCI,xNBID,LOCAL_CID,LAC/TAC,PCI,ARFCN,BAND,RSSI,RSRP,RSRQ,SINR,CQI,TA,DISTANCE,DELTA_AZI,SPEED,GPS_ACCURACY,UL,DL,BANDWIDTH,BANDWIDTHS,CA,NR_STATE,NARFCN,NR_BAND,NR_PCI,NR_SS_RSRP,NR_SS_RSRQ,NR_SS_SINR,NR_CSI_RSRP,NR_CSI_RSRQ,NR_CSI_SINR,CLF_LABEL,CLF_LOC,CLF_DESC,DATE,ROAMING,geometry,index_right,N03_001,N03_004
0,08:53:54,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,61,1227,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
1,08:53:55,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-86,-6,1.6,,180,,,0,1200,46,953,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
2,08:53:56,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-84,-6,1.6,,180,,,0,1200,56,1084,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
3,08:53:57,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-84,-6,1.6,,180,,,0,1200,72,1202,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区
4,08:53:58,35.732882,139.795405,44011,4,71727112,280184,8,211,31,1575,1800 B3,-67,-87,-5,1.6,,180,,,0,1200,65,1513,20000,20,1,none,,,,,,,,,,--,--,Cell not found in the clf database!,2022/12/07,HOME,POINT (139.79540 35.73288),110,東京都,荒川区