In [1]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('data/korea_gmonpro_20230103_152811_Sim1_45006.csv')

In [3]:
df.head(3)

,PLMN,SYSTEM,XCI,xNBID,LOCAL_CID,LAC/TAC,PCI/PSC/BSIC,ARFCN,BAND,RSSI,RSRP/RSCP,RSRQ/ECIO,SNR,CQI,TA,DISTANCE,DELTA_AZI,LAT,LON,SPEED,GPS_ACCURACY,UL,DL,BANDWIDTH,BANDWIDTHS,CA,NR_STATE,NARFCN,NR_BAND,NR_PCI,NR_SS_RSRP,NR_SS_RSRQ,NR_SS_SINR,NR_CSI_RSRP,NR_CSI_RSRQ,NR_CSI_SINR,CLF_LABEL,CLF_LOC,CLF_DESC,DATE,TIME,ROAMING
0,45006,4,51382023,200711,7,24619,386,2600,850 B5,-61,-94,-15,2.2,NaN,3.0,NaN,NaN,37.454318,126.440495,0,7,0,0,10000,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,45006,4,51382023,200711,7,24619,386,2600,850 B5,-61,-91,-16,2.2,NaN,3.0,NaN,NaN,37.454318,126.440495,0,6,0,0,10000,10,1.0,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,--,--,Cell not found in the clf database!,2023-01-03,15:28:12,Home
2,45006,4,51382023,200711,7,24619,386,2600,850 B5,-61,-91,-16,2.6,NaN,3.0,NaN,NaN,37.454318,126.440495,0,6,0,0,10000,20,1.0,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,--,--,Cell not found in the clf database!,2023-01-03,15:28:13,Home

In [4]:
import simplekml

In [5]:
kml = simplekml.Kml()

for i in range(len(df.index)):
    kml.newpoint(name=df.iloc[i]['xNBID'], coords=[(df.iloc[0]['LON'], df.iloc[0]['LAT'])])

kml.save('data/kml_sample_a.kml')

In [6]:
kml = simplekml.Kml()

for index, row in df.iterrows():
    pnt = kml.newpoint(name=row['xNBID'], coords=[(row['LON'], row['LAT'])])
    pnt.extendeddata.newdata('Index', index)
    for col in df.columns:
        pnt.extendeddata.newdata(col, row[col])
        
kml.save('data/kml_sample_b.kml')